-- GovTender Scout - Seed Data
-- Sample tenders from 45+ government portals

-- ============================================
-- SAMPLE TENDERS FROM MAJOR PORTALS
-- ============================================

INSERT INTO public.tenders (
    tender_number, title, description, portal_name, portal_url, 
    category, sub_category, organization_name, state, city,
    tender_type, bid_start_date, bid_end_date, pre_bid_date,
    estimated_value, emd_amount, eligibility_criteria, documents,
    ai_summary, ai_eligibility_match, ai_confidence_score, status
) VALUES

-- CPPP (Central Public Procurement Portal)
(
    'CPPP-2024-001',
    'Supply of Office Furniture for Central Government Offices',
    'Supply of chairs, tables, cabinets for various ministries in Delhi NCR',
    'CPPP',
    'https://eprocure.gov.in',
    'Goods',
    'Furniture',
    'Ministry of Home Affairs',
    'Delhi',
    'New Delhi',
    'goods',
    NOW() - INTERVAL '5 days',
    NOW() + INTERVAL '15 days',
    NOW() + INTERVAL '7 days',
    2500000.00,
    50000.00,
    '{"turnover": 5000000, "experience_years": 3, "certifications": ["ISO9001"], "past_projects": 5}',
    '["https://eprocure.gov.in/docs/tender_001.pdf"]',
    'Supply of office furniture worth ₹25 lakhs. Requires 3 years experience and ISO certification.',
    true,
    85.50,
    'active'
),

-- GeM (Government e-Marketplace)
(
    'GEM-2024-002',
    'Annual Maintenance Contract for Computers',
    'AMC for 500 desktop computers across multiple government offices',
    'GeM',
    'https://gem.gov.in',
    'Services',
    'IT Maintenance',
    'Department of Electronics',
    'Maharashtra',
    'Mumbai',
    'services',
    NOW() - INTERVAL '3 days',
    NOW() + INTERVAL '10 days',
    NOW() + INTERVAL '5 days',
    1500000.00,
    30000.00,
    '{"turnover": 3000000, "experience_years": 2, "certifications": ["Microsoft Partner"], "service_centers": 3}',
    '["https://gem.gov.in/docs/amc_tender.pdf"]',
    'AMC contract for computers. Need service centers in Mumbai. Microsoft partnership preferred.',
    true,
    78.20,
    'active'
),

-- Rajasthan State Portal
(
    'RJ-2024-003',
    'Construction of Primary Health Center',
    'Civil work for new PHC building with 20 beds capacity',
    'Rajasthan e-Procurement',
    'https://eproc.rajasthan.gov.in',
    'Works',
    'Healthcare Infrastructure',
    'Rajasthan Health Department',
    'Rajasthan',
    'Jaipur',
    'works',
    NOW() - INTERVAL '10 days',
    NOW() + INTERVAL '25 days',
    NOW() + INTERVAL '12 days',
    8500000.00,
    170000.00,
    '{"turnover": 15000000, "experience_years": 5, "license": "Class A Contractor", "past_phc": 2}',
    '["https://eproc.rajasthan.gov.in/docs/phc_tender.pdf", "https://eproc.rajasthan.gov.in/docs/blueprint.pdf"]',
    'Construction of 20-bed PHC. Requires Class A contractor license and healthcare infrastructure experience.',
    false,
    45.30,
    'active'
),

-- Tamil Nadu Portal
(
    'TN-2024-004',
    'Supply of Textbooks for Government Schools',
    'Printing and supply of 50,000 textbooks for classes 6-10',
    'Tamil Nadu e-Procurement',
    'https://tntenders.gov.in',
    'Goods',
    'Educational Materials',
    'Tamil Nadu Textbook Corporation',
    'Tamil Nadu',
    'Chennai',
    'goods',
    NOW() - INTERVAL '2 days',
    NOW() + INTERVAL '20 days',
    NOW() + INTERVAL '8 days',
    12000000.00,
    240000.00,
    '{"turnover": 20000000, "printing_capacity": 100000, "experience_years": 5, "iso_certified": true}',
    '["https://tntenders.gov.in/docs/textbook_spec.pdf"]',
    'Large volume textbook printing. Need high capacity printing facility and 5 years experience.',
    true,
    92.10,
    'active'
),

-- Karnataka Portal
(
    'KA-2024-005',
    'Smart City IoT Sensors Installation',
    'Installation of 1000 IoT sensors for traffic monitoring in Bangalore',
    'Karnataka e-Procurement',
    'https://eproc.karnataka.gov.in',
    'Works',
    'Smart City',
    'Bangalore Smart City Ltd',
    'Karnataka',
    'Bangalore',
    'works',
    NOW() - INTERVAL '7 days',
    NOW() + INTERVAL '30 days',
    NOW() + INTERVAL '15 days',
    45000000.00,
    900000.00,
    '{"turnover": 50000000, "experience_years": 7, "iot_projects": 5, "team_size": 50}',
    '["https://eproc.karnataka.gov.in/docs/iot_specs.pdf", "https://eproc.karnataka.gov.in/docs/technical_requirements.pdf"]',
    'Smart city IoT project. Requires proven track record in IoT installations and large technical team.',
    false,
    35.80,
    'active'
),

-- ISRO Tender
(
    'ISRO-2024-006',
    'Precision Manufacturing Components',
    'Manufacturing of high-precision aerospace components for satellite systems',
    'ISRO',
    'https://www.isro.gov.in/Tenders.html',
    'Goods',
    'Aerospace',
    'Indian Space Research Organisation',
    'Karnataka',
    'Bangalore',
    'goods',
    NOW() - INTERVAL '15 days',
    NOW() + INTERVAL '35 days',
    NOW() + INTERVAL '18 days',
    75000000.00,
    1500000.00,
    '{"turnover": 100000000, "experience_years": 10, "certifications": ["AS9100", "NADCAP"], "clean_room": true}',
    '["https://isro.gov.in/docs/precision_specs.pdf"]',
    'High-precision aerospace components. Requires AS9100 certification and clean room facilities.',
    false,
    28.50,
    'active'
),

-- Railway Tender (IREPS)
(
    'IREPS-2024-007',
    'Supply of Railway Sleepers',
    'Supply of 50,000 pre-stressed concrete sleepers for railway tracks',
    'IREPS',
    'https://www.ireps.gov.in',
    'Goods',
    'Railway Infrastructure',
    'Indian Railways',
    'Uttar Pradesh',
    'Lucknow',
    'goods',
    NOW() - INTERVAL '4 days',
    NOW() + INTERVAL '18 days',
    NOW() + INTERVAL '9 days',
    32000000.00,
    640000.00,
    '{"turnover": 40000000, "experience_years": 5, "manufacturing_unit": true, "railway_approval": true}',
    '["https://ireps.gov.in/docs/sleeper_specs.pdf"]',
    'Concrete railway sleepers. Must have railway approval and own manufacturing unit.',
    true,
    88.90,
    'active'
),

-- DRDO Tender
(
    'DRDO-2024-008',
    'Electronic Warfare Systems Components',
    'Supply of specialized electronic components for defense systems',
    'DRDO',
    'https://www.drdo.gov.in/drdo/tenders',
    'Goods',
    'Defense Electronics',
    'Defence Research and Development Organisation',
    'Telangana',
    'Hyderabad',
    'goods',
    NOW() - INTERVAL '20 days',
    NOW() + INTERVAL '40 days',
    NOW() + INTERVAL '22 days',
    95000000.00,
    1900000.00,
    '{"turnover": 150000000, "experience_years": 10, "security_clearance": "Secret", "defense_projects": 8}',
    '["https://drdo.gov.in/docs/ew_components.pdf"]',
    'Defense electronics components. Requires secret security clearance and defense sector experience.',
    false,
    22.40,
    'active'
),

-- Maharashtra Portal
(
    'MH-2024-009',
    'Road Construction Project',
    'Construction of 25 km two-lane road with bridges',
    'Maharashtra e-Procurement',
    'https://mahatenders.gov.in',
    'Works',
    'Roads & Bridges',
    'Maharashtra PWD',
    'Maharashtra',
    'Pune',
    'works',
    NOW() - INTERVAL '8 days',
    NOW() + INTERVAL '45 days',
    NOW() + INTERVAL '20 days',
    125000000.00,
    2500000.00,
    '{"turnover": 200000000, "experience_years": 10, "license": "Class AAA", "equipment": true}',
    '["https://mahatenders.gov.in/docs/road_project.pdf"]',
    'Major road construction with bridges. Requires Class AAA license and heavy equipment ownership.',
    false,
    31.20,
    'active'
),

-- Kerala Portal
(
    'KL-2024-010',
    'Hospital Medical Equipment',
    'Supply and installation of ICU equipment for district hospital',
    'Kerala e-Procurement',
    'https://etenders.kerala.gov.in',
    'Goods',
    'Medical Equipment',
    'Kerala Health Services',
    'Kerala',
    'Thiruvananthapuram',
    'goods',
    NOW() - INTERVAL '1 day',
    NOW() + INTERVAL '12 days',
    NOW() + INTERVAL '6 days',
    18000000.00,
    360000.00,
    '{"turnover": 25000000, "experience_years": 5, "fda_approved": true, "service_network": true}',
    '["https://etenders.kerala.gov.in/docs/icu_equipment.pdf"]',
    'ICU medical equipment supply. FDA approval mandatory and service network required.',
    true,
    81.70,
    'active'
),

-- Telangana Portal (Expiring Soon)
(
    'TS-2024-011',
    'Cloud Infrastructure for E-Governance',
    'Setting up cloud infrastructure for state e-governance services',
    'Telangana e-Procurement',
    'https://tender.telangana.gov.in',
    'Services',
    'Cloud Computing',
    'Telangana State IT Department',
    'Telangana',
    'Hyderabad',
    'services',
    NOW() - INTERVAL '12 days',
    NOW() + INTERVAL '3 days',
    NOW() + INTERVAL '1 day',
    65000000.00,
    1300000.00,
    '{"turnover": 80000000, "experience_years": 7, "cloud_certifications": ["AWS", "Azure"], "data_center": true}',
    '["https://tender.telangana.gov.in/docs/cloud_rfp.pdf"]',
    'Cloud infrastructure project. AWS/Azure certifications required. URGENT: 3 days left!',
    true,
    94.30,
    'active'
),

-- Gujarat Portal
(
    'GJ-2024-012',
    'Solar Power Plant Installation',
    'Installation of 5 MW solar power plant for government buildings',
    'Gujarat e-Procurement',
    'https://gjeproc.gujarat.gov.in',
    'Works',
    'Renewable Energy',
    'Gujarat Energy Development Agency',
    'Gujarat',
    'Gandhinagar',
    'works',
    NOW() - INTERVAL '6 days',
    NOW() + INTERVAL '28 days',
    NOW() + INTERVAL '14 days',
    185000000.00,
    3700000.00,
    '{"turnover": 250000000, "experience_years": 8, "solar_projects": 10, "mnre_empanelled": true}',
    '["https://gjeproc.gujarat.gov.in/docs/solar_project.pdf"]',
    '5 MW solar plant. MNRE empanelment required. Large scale renewable energy project.',
    false,
    42.60,
    'active'
),

-- West Bengal Portal
(
    'WB-2024-013',
    'Water Treatment Plant',
    'Construction of water treatment plant with 10 MLD capacity',
    'West Bengal e-Procurement',
    'https://wbtenders.gov.in',
    'Works',
    'Water Infrastructure',
    'Kolkata Municipal Corporation',
    'West Bengal',
    'Kolkata',
    'works',
    NOW() - INTERVAL '9 days',
    NOW() + INTERVAL '32 days',
    NOW() + INTERVAL '16 days',
    95000000.00,
    1900000.00,
    '{"turnover": 120000000, "experience_years": 7, "water_projects": 5, "environmental_clearance": true}',
    '["https://wbtenders.gov.in/docs/wtp_project.pdf"]',
    'Water treatment plant construction. Environmental clearance mandatory. 10 MLD capacity.',
    true,
    76.40,
    'active'
),

-- Odisha Portal
(
    'OD-2024-014',
    'Mining Equipment Supply',
    'Supply of excavators and dumpers for coal mining operations',
    'Odisha e-Procurement',
    'https://tendersodisha.gov.in',
    'Goods',
    'Mining Equipment',
    'Odisha Coal Authority',
    'Odisha',
    'Bhubaneswar',
    'goods',
    NOW() - INTERVAL '5 days',
    NOW() + INTERVAL '22 days',
    NOW() + INTERVAL '11 days',
    220000000.00,
    4400000.00,
    '{"turnover": 300000000, "experience_years": 10, "oem_authorization": true, "mining_projects": 8}',
    '["https://tendersodisha.gov.in/docs/mining_equip.pdf"]',
    'Heavy mining equipment supply. OEM authorization required. High value contract.',
    false,
    38.90,
    'active'
),

-- Punjab Portal
(
    'PB-2024-015',
    'Agricultural Machinery Distribution',
    'Supply of tractors and harvesters to farmers under subsidy scheme',
    'Punjab e-Procurement',
    'https://eproc.punjab.gov.in',
    'Goods',
    'Agricultural Equipment',
    'Punjab Agriculture Department',
    'Punjab',
    'Chandigarh',
    'goods',
    NOW() - INTERVAL '3 days',
    NOW() + INTERVAL '16 days',
    NOW() + INTERVAL '8 days',
    85000000.00,
    1700000.00,
    '{"turnover": 100000000, "experience_years": 5, "dealer_network": true, "oem_tieup": true}',
    '["https://eproc.punjab.gov.in/docs/agri_machinery.pdf"]',
    'Agricultural machinery for subsidy scheme. Dealer network and OEM tie-up essential.',
    true,
    83.50,
    'active'
),

-- Haryana Portal
(
    'HR-2024-016',
    'IT Park Infrastructure Development',
    'Development of IT park with commercial complexes',
    'Haryana e-Procurement',
    'https://etenders.hry.nic.in',
    'Works',
    'Commercial Infrastructure',
    'HSIIDC',
    'Haryana',
    'Gurugram',
    'works',
    NOW() - INTERVAL '11 days',
    NOW() + INTERVAL '38 days',
    NOW() + INTERVAL '19 days',
    450000000.00,
    9000000.00,
    '{"turnover": 500000000, "experience_years": 12, "license": "Class AAAA", "commercial_projects": 15}',
    '["https://etenders.hry.nic.in/docs/it_park.pdf"]',
    'Large IT park development. Mega infrastructure project requiring highest contractor class.',
    false,
    25.70,
    'active'
),

-- Bihar Portal
(
    'BR-2024-017',
    'Bridge Construction over Ganga River',
    'Construction of 2.5 km bridge with approach roads',
    'Bihar e-Procurement',
    'https://eproc2.bihar.gov.in',
    'Works',
    'Bridges',
    'Bihar Road Development Corporation',
    'Bihar',
    'Patna',
    'works',
    NOW() - INTERVAL '14 days',
    NOW() + INTERVAL '50 days',
    NOW() + INTERVAL '25 days',
    680000000.00,
    13600000.00,
    '{"turnover": 800000000, "experience_years": 15, "bridge_projects": 8, "specialized_equipment": true}',
    '["https://eproc2.bihar.gov.in/docs/ganga_bridge.pdf"]',
    'Major bridge construction over Ganga. Requires extensive bridge building experience.',
    false,
    19.80,
    'active'
),

-- Assam Portal
(
    'AS-2024-018',
    'Tea Processing Machinery',
    'Supply and installation of automated tea processing units',
    'Assam e-Procurement',
    'https://assamtenders.gov.in',
    'Goods',
    'Food Processing',
    'Assam Tea Corporation',
    'Assam',
    'Guwahati',
    'goods',
    NOW() - INTERVAL '7 days',
    NOW() + INTERVAL '24 days',
    NOW() + INTERVAL '12 days',
    42000000.00,
    840000.00,
    '{"turnover": 50000000, "experience_years": 6, "food_processing": true, "after_sales": true}',
    '["https://assamtenders.gov.in/docs/tea_machinery.pdf"]',
    'Automated tea processing units. Food processing experience and after-sales support needed.',
    true,
    79.60,
    'active'
),

-- Jharkhand Portal
(
    'JH-2024-019',
    'Steel Plant Expansion',
    'Expansion of existing steel plant with new blast furnace',
    'Jharkhand e-Procurement',
    'https://jharkhandtenders.gov.in',
    'Works',
    'Industrial',
    'Jharkhand Steel Authority',
    'Jharkhand',
    'Jamshedpur',
    'works',
    NOW() - INTERVAL '16 days',
    NOW() + INTERVAL '55 days',
    NOW() + INTERVAL '28 days',
    890000000.00,
    17800000.00,
    '{"turnover": 1000000000, "experience_years": 15, "steel_projects": 10, "safety_certification": true}',
    '["https://jharkhandtenders.gov.in/docs/steel_expansion.pdf"]',
    'Steel plant expansion project. Massive industrial project requiring proven track record.',
    false,
    15.30,
    'active'
),

-- Himachal Pradesh Portal
(
    'HP-2024-020',
    'Hydroelectric Project Components',
    'Supply of turbines and generators for 50 MW hydro project',
    'Himachal Pradesh e-Procurement',
    'https://hptenders.gov.in',
    'Goods',
    'Power Generation',
    'HP Power Corporation',
    'Himachal Pradesh',
    'Shimla',
    'goods',
    NOW() - INTERVAL '10 days',
    NOW() + INTERVAL '35 days',
    NOW() + INTERVAL '18 days',
    320000000.00,
    6400000.00,
    '{"turnover": 400000000, "experience_years": 12, "hydro_projects": 6, "oem_partner": true}',
    '["https://hptenders.gov.in/docs/hydro_turbines.pdf"]',
    'Hydroelectric turbines and generators. OEM partnership and hydro experience critical.',
    false,
    33.40,
    'active'
),

-- Uttarakhand Portal
(
    'UK-2024-021',
    'Tourism Infrastructure Development',
    'Development of tourist resorts and adventure facilities',
    'Uttarakhand e-Procurement',
    'https://uktenders.gov.in',
    'Works',
    'Tourism',
    'Uttarakhand Tourism Board',
    'Uttarakhand',
    'Dehradun',
    'works',
    NOW() - INTERVAL '4 days',
    NOW() + INTERVAL '26 days',
    NOW() + INTERVAL '13 days',
    145000000.00,
    2900000.00,
    '{"turnover": 180000000, "experience_years": 8, "tourism_projects": 5, "eco_friendly": true}',
    '["https://uktenders.gov.in/docs/tourism_resort.pdf"]',
    'Tourism infrastructure in eco-sensitive zone. Eco-friendly construction practices required.',
    true,
    71.20,
    'active'
),

-- Startup India Portal
(
    'STARTUP-2024-022',
    'Innovative Waste Management Solution',
    'Deployment of AI-based waste segregation system for smart cities',
    'Startup India',
    'https://www.startupindia.gov.in/content/sih/en/public_procurement.html',
    'Services',
    'Waste Management',
    'Ministry of Housing and Urban Affairs',
    'Delhi',
    'New Delhi',
    'services',
    NOW() - INTERVAL '2 days',
    NOW() + INTERVAL '14 days',
    NOW() + INTERVAL '7 days',
    28000000.00,
    560000.00,
    '{"startup_registered": true, "dpiit_recognition": true, "pilot_project": true, "team_size": 10}',
    '["https://startupindia.gov.in/docs/waste_mgmt.pdf"]',
    'AI-based waste management for startups. DPIIT recognition mandatory. Innovation-focused.',
    true,
    89.70,
    'active'
),

-- NTPC Tender
(
    'NTPC-2024-023',
    'Coal Handling Plant Automation',
    'Automation of coal handling system with IoT sensors',
    'NTPC',
    'https://www.ntpctender.com',
    'Services',
    'Plant Automation',
    'NTPC Limited',
    'Uttar Pradesh',
    'Singrauli',
    'services',
    NOW() - INTERVAL '8 days',
    NOW() + INTERVAL '30 days',
    NOW() + INTERVAL '15 days',
    175000000.00,
    3500000.00,
    '{"turnover": 200000000, "experience_years": 10, "power_plant_projects": 8, "iot_expertise": true}',
    '["https://ntpctender.com/docs/chp_automation.pdf"]',
    'Coal plant automation with IoT. Power sector experience and IoT expertise essential.',
    true,
    84.10,
    'active'
),

-- BSNL Tender
(
    'BSNL-2024-024',
    '5G Network Equipment',
    'Supply and installation of 5G base station equipment',
    'BSNL',
    'https://www.bsnl.co.in/opencms/bsnl/BSNL/about_us/tender.html',
    'Goods',
    'Telecom',
    'Bharat Sanchar Nigam Limited',
    'Pan India',
    'New Delhi',
    'goods',
    NOW() - INTERVAL '6 days',
    NOW() + INTERVAL '28 days',
    NOW() + INTERVAL '14 days',
    520000000.00,
    10400000.00,
    '{"turnover": 600000000, "experience_years": 10, "telecom_certifications": ["3GPP"], "pan_india_service": true}',
    '["https://bsnl.co.in/docs/5g_equipment.pdf"]',
    '5G network equipment rollout. 3GPP certification and pan-India service capability needed.',
    false,
    29.80,
    'active'
),

-- NHAI Tender
(
    'NHAI-2024-025',
    'Highway Widening Project',
    'Widening of 150 km national highway to 6 lanes',
    'NHAI',
    'https://www.nhai.gov.in',
    'Works',
    'Highways',
    'National Highways Authority of India',
    'Multiple States',
    'New Delhi',
    'works',
    NOW() - INTERVAL '12 days',
    NOW() + INTERVAL '60 days',
    NOW() + INTERVAL '30 days',
    1250000000.00,
    25000000.00,
    '{"turnover": 1500000000, "experience_years": 15, "nhai_projects": 12, "equipment_fleet": true}',
    '["https://nhai.gov.in/docs/highway_widening.pdf"]',
    'Mega highway widening project. One of the largest infrastructure tenders. Extensive experience required.',
    false,
    12.50,
    'active'
);

-- ============================================
-- UPDATE STATISTICS
-- ============================================
ANALYZE public.tenders;

-- Show summary
SELECT 
    'Seed Data Summary' as info,
    COUNT(*) as total_tenders,
    COUNT(CASE WHEN ai_eligibility_match = true THEN 1 END) as ai_matched,
    COUNT(DISTINCT portal_name) as portals_covered,
    COUNT(DISTINCT state) as states_covered,
    MIN(bid_end_date) as earliest_deadline,
    MAX(estimated_value) as highest_value
FROM public.tenders;
